<a href="https://colab.research.google.com/github/Sifiso-Mazibuko/Pandas/blob/main/pandas_dataframe_practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas DataFrame practical

## Dictionary --> DataFrame

In [ ]:
import pandas as pd

Anna is 8 years old and has a dog. Ben is 10 years old and has a cat. Chris is 12 years old and has a parrot. Dean is 7 years old and has a dog. Edward is 15 years old and has a goldfish

Create a Pandas DataFrame named *df_from_dict* that lists the above information in three columns with headings "Name", "Age" and "Pet"

In [ ]:
# enter code here
df_from_dict = {'Name':['Anna', 'Ben', 'Chris',' Dean', 'Edward'],
                'Age' :[8, 10, 12, 7, 15],
                'Pet' :['dog', 'cat', 'parrot', 'dog', 'goldfish']
                }

In [ ]:
df_from_dict = pd.DataFrame(df_from_dict)

In [ ]:
df_from_dict

     Name  Age       Pet
0    Anna    8       dog
1     Ben   10       cat
2   Chris   12    parrot
3    Dean    7       dog
4  Edward   15  goldfish

Determine Dean's pet by only using Pandas Dataframes commands

## CSV / Excel sheet --> DataFrame

Create a folder named pandas_df_prac in your Drive.
Upload the Excel sheet "sample_sales.xlsx" to that folder.
Now mount your Google Drive and define a variable "file_path" that specifies the path to that Excel sheet

In [ ]:
# enter code here
from google.colab from files
file_path = files.upload()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
file_path = '/content/drive/MyDrive/pandas_df_prac/sample_sales.xlsx'

Create a dataframe **`df1`** from the first sheet of the "sample_sales.xlsx" Excel file.

In [ ]:
df1=pd.read_excel(file_path)

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~
1,Australia and Oceania,Tuvalu,Baby Food,H,2010-05-28,1582243.50,951410.5
2,~,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
3,Central America and the Caribbean,Grenada,Cereal,C,2012-08-22,328376.44,248406.36
4,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~
5,Sub-Saharan Africa,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
6,Sub-Saharan Africa,Rwanda,Office Supplies,L,2013-02-01,2657347.52,639077.5
7,Australia and Oceania,Solomon Islands,Baby Food,C,2015-02-04,474115.08,285087.64
8,Sub-Saharan Africa,Angola,Household,M,2011-04-23,2104134.98,~
9,Sub-Saharan Africa,Angola,Household,M,2011-04-23,2104134.98,~
10,Sub-Saharan Africa,~,Vegetables,H,2012-07-17,734896.26,510216.66
11,Sub-Saharan Africa,Republic of the Congo,Personal Care,M,2015-07-14,343986.90,152114.2
12,Sub-Saharan Africa,Senegal,Cereal,H,2014-04-18,772106.23,584073.87
13,Asia,Kyrgyzstan,Vegetables,H,2011-06-24,11275.32,~
14,Sub-Saharan Africa,Cape Verde,Clothes,H,2014-08-02,149381.12,306097.92
15,Asia,Bangladesh,Clothes,L,2017-01-13,296145.92,606834.72
16,Europe,Bulgaria,Clothes,M,2012-04-23,59960.32,122865.12
17,Central America and the Caribbean,Honduras,Household,H,2017-02-08,4509793.96,1487261.02
18,Asia,Mongolia,Personal Care,C,2014-02-19,277739.67,122819.06
19,Europe,Bulgaria,Clothes,M,2012-04-23,59960.32,122865.12
20,Asia,Sri Lanka,Cosmetics,M,2016-11-19,1830670.16,1208744.24
21,Sub-Saharan Africa,Cameroon,Beverages,C,2015-04-01,172619.70,85033.8
22,Asia,Turkmenistan,Household,L,2010-12-30,1924728.20,634745.9
23,Australia and Oceania,East Timor,Meat,L,2012-07-31,2154588.52,337937.6
24,Europe,Norway,Baby Food,L,2014-05-14,1187679.00,714157
25,Sub-Saharan Africa,The Gambia,Household,L,2012-05-26,1191019.80,392780.1
26,Europe,Portugal,Baby Food,H,2015-07-31,202941.66,122029.78
27,Central America and the Caribbean,Honduras,Snacks,L,2016-06-30,216804.00,122686.5
28,Australia and Oceania,New Zealand,Fruits,H,2014-09-08,15134.04,5270.67
29,Europe,Moldova,Personal Care,L,2016-05-07,287316.90,127054.2
30,Europe,France,Cosmetics,H,2017-05-22,477943.95,315574.05
31,Australia and Oceania,Kiribati,Fruits,M,2014-10-13,37354.16,13009.18
32,Sub-Saharan Africa,Mali,Fruits,L,2010-05-07,40288.24,14031.02
33,Europe,Norway,Beverages,C,2014-07-18,162891.96,80241.84
34,Sub-Saharan Africa,The Gambia,Household,L,2012-05-26,1191019.80,392780.1
35,Europe,Switzerland,Cosmetics,M,2012-09-17,2280701.13,1505888.07
36,Sub-Saharan Africa,South Sudan,Personal Care,C,2013-12-29,120423.75,53252.5
37,Australia and Oceania,Australia,Office Supplies,C,2015-10-27,1534983.04,369155
38,Asia,Myanmar,Household,H,2015-01-16,4145955.00,1367272.5
39,Sub-Saharan Africa,Djibouti,Snacks,M,2017-02-25,713942.88,404010.78
40,Central America and the Caribbean,Costa Rica,Personal Care,L,2017-05-08,363198.03,160609.54
41,Middle East and North Africa,Syria,Fruits,L,2011-11-22,26185.28,9119.44
42,Sub-Saharan Africa,The Gambia,Meat,M,2017-01-14,1738477.23,272672.4
43,Central America and the Caribbean,Costa Rica,Personal Care,L,2017-05-08,363198.03,160609.54
44,Asia,Brunei,Office Supplies,L,2012-04-01,3521431.68,846885
45,Europe,Bulgaria,Office Supplies,M,2012-02-16,2093015.52,503358.75
46,Sub-Saharan Africa,Niger,Personal Care,H,2017-03-11,170860.05,75555.9
47,Middle East and North Africa,Azerbaijan,Cosmetics,M,2010-02-06,1904929.22,1257775.58
48,Sub-Saharan Africa,The Gambia,Cereal,H,2012-06-07,247921.87,187545.03

Create a dataframe **`df2`** from the second sheet of the Excel file.
* Note that this dataset does not have any headings.
* Add the same headings to this dataframe as in the first sheet, namely:

"Region", "Country", "Item Type", "Order Priority", "Order Date", "Total Cost", "Total Profit"

In [ ]:
second_path = '/content/drive/MyDrive/pandas_df_prac/sample_sales2.xlsx'

In [ ]:
headings = ['Region', 'Country', 'Item Type', 'Order Priority', 'Order Date', 'Total Cost', 'Total Profit']
df2=pd.read_excel(second_path, sheet_name = 'Sample_Sales_2')
df2.head()

,Europe,Monaco,Baby Food,H,2012-05-29 00:00:00,1373243.88,825738.04
0,Australia and Oceania,Samoa,Cosmetics,H,2013-07-20 00:00:00,2542187.82,1678540.98
1,Europe,Spain,Household,L,2012-10-21 00:00:00,2267963.02,747939.49
2,Middle East and North Africa,Lebanon,Clothes,L,2012-31-09,282562.56,579000.96
3,Middle East and North Africa,Iran,Cosmetics,H,2016-15-13,1708748.37,1128242.43
4,Sub-Saharan Africa,Zambia,Snacks,L,2011-01-04 00:00:00,398042.40,225246.90

Create a dataframe **`df3`** from the third sheet of the Excel file.
* Note that you will need to skip the first few lines

In [ ]:
third_path = '/content/drive/MyDrive/pandas_df_prac/sample_sales3.xlsx'

In [ ]:
df3 = pd.read_excel(third_path, sheet_name='Sample_Sales_3', skiprows=4)

In [ ]:
df3

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Middle East and North Africa,Azerbaijan,Office Supplies,M,2012-06-13,1060944.16,255151.25
1,Europe,Romania,Cosmetics,H,2010-11-26,2082940.30,1375311.70
2,Central America and the Caribbean,Nicaragua,Beverages,C,2011-02-05,259279.24,127722.96
3,Sub-Saharan Africa,Mali,Clothes,M,2011-07-26,31825.92,65214.72
4,Asia,Malaysia,Fruits,L,2011-11-11,43367.64,15103.47
5,Sub-Saharan Africa,Sierra Leone,Vegetables,C,2016-06-01,135031.05,93748.05
6,North America,Mexico,Personal Care,M,2015-07-30,326815.89,144521.02
7,Sub-Saharan Africa,Mozambique,Household,L,2012-02-10,2697132.18,889472.91

Create a dataframe **`df_concat_13`** that concatenates the dataframes **`df1`** and **`df3`** on the row axis.

NB: remember to reset your index!

In [ ]:
df_concat_13 = pd.concat([df1, df3], axis=0)
df_concat_13.reset_index(drop=True)

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~
1,Australia and Oceania,Tuvalu,Baby Food,H,2010-05-28,1582243.50,951410.5
2,~,Sao Tome and Principe,Fruits,C,2014-06-20,56065.84,19525.82
3,Central America and the Caribbean,Grenada,Cereal,C,2012-08-22,328376.44,248406.36
4,Europe,Russia,Office Supplies,L,2014-05-02,933903.84,~
...,...,...,...,...,...,...,...
93,Asia,Brunei,Office Supplies,L,2012-04-01,3521431.68,846885
94,Europe,Bulgaria,Office Supplies,M,2012-02-16,2093015.52,503358.75
95,Sub-Saharan Africa,Niger,Personal Care,H,2017-03-11,170860.05,75555.9
96,Middle East and North Africa,Azerbaijan,Cosmetics,M,2010-02-06,1904929.22,1257775.58
97,Sub-Saharan Africa,The Gambia,Cereal,H,2012-06-07,247921.87,187545.03

## Replacing and removing

For dataframe **`df1`**, column name "Order Priority":
* replace "H" with "High"
* replace "M" with "Medium"
* replace "L" with "Low"

(Keep the dataframe name **`df1`**)


Note: you can either write a separate line of code for each of the replacements, OR you can do all the replacements with a single line of code...

In [ ]:
df1['Order Priority'] = df1['Order Priority'].replace(['H','M','L','C'],['High', 'Medium', 'Low', 'Constant'])
df1.reset_index(drop=True)
df1.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,~
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28,1582243.50,951410.5
2,~,Sao Tome and Principe,Fruits,Constant,2014-06-20,56065.84,19525.82
3,Central America and the Caribbean,Grenada,Cereal,Constant,2012-08-22,328376.44,248406.36
4,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,~

For dataframe **`df1`**, replace all entries containing '~' with NaN values.

NB: remember to import the numpy library!

In [ ]:
import numpy as np

In [ ]:
# Enter code here
df1.replace('~', np.nan, inplace=True)
df1.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28,1582243.50,951410.50
2,NaN,Sao Tome and Principe,Fruits,Constant,2014-06-20,56065.84,19525.82
3,Central America and the Caribbean,Grenada,Cereal,Constant,2012-08-22,328376.44,248406.36
4,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN

For dataframe **`df1`**, remove all rows in the dataframe where there is a "C" in the "Order Priority" column.

In [ ]:
df6 =df1[~df1['Order Priority'].isin(['Constant'])]

In [ ]:
df6

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28,1582243.50,951410.50
4,Europe,Russia,Office Supplies,Low,2014-05-02,933903.84,NaN
6,Sub-Saharan Africa,Rwanda,Office Supplies,Low,2013-02-01,2657347.52,639077.50
8,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23,2104134.98,NaN
9,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23,2104134.98,NaN
10,Sub-Saharan Africa,NaN,Vegetables,High,2012-07-17,734896.26,510216.66
11,Sub-Saharan Africa,Republic of the Congo,Personal Care,Medium,2015-07-14,343986.90,152114.20
12,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18,772106.23,584073.87
13,Asia,Kyrgyzstan,Vegetables,High,2011-06-24,11275.32,NaN
14,Sub-Saharan Africa,Cape Verde,Clothes,High,2014-08-02,149381.12,306097.92
15,Asia,Bangladesh,Clothes,Low,2017-01-13,296145.92,606834.72
16,Europe,Bulgaria,Clothes,Medium,2012-04-23,59960.32,122865.12
17,Central America and the Caribbean,Honduras,Household,High,2017-02-08,4509793.96,1487261.02
19,Europe,Bulgaria,Clothes,Medium,2012-04-23,59960.32,122865.12
20,Asia,Sri Lanka,Cosmetics,Medium,2016-11-19,1830670.16,1208744.24
22,Asia,Turkmenistan,Household,Low,2010-12-30,1924728.20,634745.90
23,Australia and Oceania,East Timor,Meat,Low,2012-07-31,2154588.52,337937.60
24,Europe,Norway,Baby Food,Low,2014-05-14,1187679.00,714157.00
25,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26,1191019.80,392780.10
26,Europe,Portugal,Baby Food,High,2015-07-31,202941.66,122029.78
27,Central America and the Caribbean,Honduras,Snacks,Low,2016-06-30,216804.00,122686.50
28,Australia and Oceania,New Zealand,Fruits,High,2014-09-08,15134.04,5270.67
29,Europe,Moldova,Personal Care,Low,2016-05-07,287316.90,127054.20
30,Europe,France,Cosmetics,High,2017-05-22,477943.95,315574.05
31,Australia and Oceania,Kiribati,Fruits,Medium,2014-10-13,37354.16,13009.18
32,Sub-Saharan Africa,Mali,Fruits,Low,2010-05-07,40288.24,14031.02
34,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26,1191019.80,392780.10
35,Europe,Switzerland,Cosmetics,Medium,2012-09-17,2280701.13,1505888.07
38,Asia,Myanmar,Household,High,2015-01-16,4145955.00,1367272.50
39,Sub-Saharan Africa,Djibouti,Snacks,Medium,2017-02-25,713942.88,404010.78
40,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08,363198.03,160609.54
41,Middle East and North Africa,Syria,Fruits,Low,2011-11-22,26185.28,9119.44
42,Sub-Saharan Africa,The Gambia,Meat,Medium,2017-01-14,1738477.23,272672.40
43,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08,363198.03,160609.54
44,Asia,Brunei,Office Supplies,Low,2012-04-01,3521431.68,846885.00
45,Europe,Bulgaria,Office Supplies,Medium,2012-02-16,2093015.52,503358.75
46,Sub-Saharan Africa,Niger,Personal Care,High,2017-03-11,170860.05,75555.90
47,Middle East and North Africa,Azerbaijan,Cosmetics,Medium,2010-02-06,1904929.22,1257775.58
48,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07,247921.87,187545.03

Give the Order Priority of the third sample/row in this new table by using Pandas commands.

Are you getting an error message? Why?

Fix the error by...

In [ ]:
# Enter code here (if applicable)
third_row_priority = df1['Order Priority'][2]

The Order Priority of the third sample is therefore:

Create a dataframe **`df_cereal`**. This dataframe should only contain the rows of **`df1`** where the "Item Type" entry is "Cereal"
* remember to reset the index

In [ ]:
df_cereal = df1[df1['Item Type'] == 'Cereal'].reset_index(drop=True)

In [ ]:
df_cereal

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Central America and the Caribbean,Grenada,Cereal,Constant,2012-08-22,328376.44,248406.36
1,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18,772106.23,584073.87
2,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07,247921.87,187545.03

Remove the column "Total Cost" and "Total Profit" in dataframe **`df1`**.

(Keep the dataframe name **`df1`**)

In [ ]:
df1.drop(columns=['Total Cost', 'Total Profit'], inplace=True)

In [ ]:
df1

,Region,Country,Item Type,Order Priority,Order Date
0,Europe,Russia,Office Supplies,Low,2014-05-02
1,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28
2,NaN,Sao Tome and Principe,Fruits,Constant,2014-06-20
3,Central America and the Caribbean,Grenada,Cereal,Constant,2012-08-22
4,Europe,Russia,Office Supplies,Low,2014-05-02
5,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Constant,2014-06-20
6,Sub-Saharan Africa,Rwanda,Office Supplies,Low,2013-02-01
7,Australia and Oceania,Solomon Islands,Baby Food,Constant,2015-02-04
8,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23
9,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23
10,Sub-Saharan Africa,NaN,Vegetables,High,2012-07-17
11,Sub-Saharan Africa,Republic of the Congo,Personal Care,Medium,2015-07-14
12,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18
13,Asia,Kyrgyzstan,Vegetables,High,2011-06-24
14,Sub-Saharan Africa,Cape Verde,Clothes,High,2014-08-02
15,Asia,Bangladesh,Clothes,Low,2017-01-13
16,Europe,Bulgaria,Clothes,Medium,2012-04-23
17,Central America and the Caribbean,Honduras,Household,High,2017-02-08
18,Asia,Mongolia,Personal Care,Constant,2014-02-19
19,Europe,Bulgaria,Clothes,Medium,2012-04-23
20,Asia,Sri Lanka,Cosmetics,Medium,2016-11-19
21,Sub-Saharan Africa,Cameroon,Beverages,Constant,2015-04-01
22,Asia,Turkmenistan,Household,Low,2010-12-30
23,Australia and Oceania,East Timor,Meat,Low,2012-07-31
24,Europe,Norway,Baby Food,Low,2014-05-14
25,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26
26,Europe,Portugal,Baby Food,High,2015-07-31
27,Central America and the Caribbean,Honduras,Snacks,Low,2016-06-30
28,Australia and Oceania,New Zealand,Fruits,High,2014-09-08
29,Europe,Moldova,Personal Care,Low,2016-05-07
30,Europe,France,Cosmetics,High,2017-05-22
31,Australia and Oceania,Kiribati,Fruits,Medium,2014-10-13
32,Sub-Saharan Africa,Mali,Fruits,Low,2010-05-07
33,Europe,Norway,Beverages,Constant,2014-07-18
34,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26
35,Europe,Switzerland,Cosmetics,Medium,2012-09-17
36,Sub-Saharan Africa,South Sudan,Personal Care,Constant,2013-12-29
37,Australia and Oceania,Australia,Office Supplies,Constant,2015-10-27
38,Asia,Myanmar,Household,High,2015-01-16
39,Sub-Saharan Africa,Djibouti,Snacks,Medium,2017-02-25
40,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08
41,Middle East and North Africa,Syria,Fruits,Low,2011-11-22
42,Sub-Saharan Africa,The Gambia,Meat,Medium,2017-01-14
43,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08
44,Asia,Brunei,Office Supplies,Low,2012-04-01
45,Europe,Bulgaria,Office Supplies,Medium,2012-02-16
46,Sub-Saharan Africa,Niger,Personal Care,High,2017-03-11
47,Middle East and North Africa,Azerbaijan,Cosmetics,Medium,2010-02-06
48,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07

Some of the entries in **`df1`** are duplicates.
If the same "Country" and "Item type" entries appear in more than one row, only keep the **`last`** entry and remove the rest of the duplicates. Keep the name of the dataframe **`df1`**
* remember to reset the index

In [ ]:
df1 = df1.drop_duplicates(subset=['Country', 'Item Type'], keep='last').reset_index(drop=True)

In [ ]:
df1

,Region,Country,Item Type,Order Priority,Order Date
0,Australia and Oceania,Tuvalu,Baby Food,High,2010-05-28
1,Central America and the Caribbean,Grenada,Cereal,Constant,2012-08-22
2,Europe,Russia,Office Supplies,Low,2014-05-02
3,Sub-Saharan Africa,Sao Tome and Principe,Fruits,Constant,2014-06-20
4,Sub-Saharan Africa,Rwanda,Office Supplies,Low,2013-02-01
5,Australia and Oceania,Solomon Islands,Baby Food,Constant,2015-02-04
6,Sub-Saharan Africa,Angola,Household,Medium,2011-04-23
7,Sub-Saharan Africa,NaN,Vegetables,High,2012-07-17
8,Sub-Saharan Africa,Republic of the Congo,Personal Care,Medium,2015-07-14
9,Sub-Saharan Africa,Senegal,Cereal,High,2014-04-18
10,Asia,Kyrgyzstan,Vegetables,High,2011-06-24
11,Sub-Saharan Africa,Cape Verde,Clothes,High,2014-08-02
12,Asia,Bangladesh,Clothes,Low,2017-01-13
13,Central America and the Caribbean,Honduras,Household,High,2017-02-08
14,Asia,Mongolia,Personal Care,Constant,2014-02-19
15,Europe,Bulgaria,Clothes,Medium,2012-04-23
16,Asia,Sri Lanka,Cosmetics,Medium,2016-11-19
17,Sub-Saharan Africa,Cameroon,Beverages,Constant,2015-04-01
18,Asia,Turkmenistan,Household,Low,2010-12-30
19,Australia and Oceania,East Timor,Meat,Low,2012-07-31
20,Europe,Norway,Baby Food,Low,2014-05-14
21,Europe,Portugal,Baby Food,High,2015-07-31
22,Central America and the Caribbean,Honduras,Snacks,Low,2016-06-30
23,Australia and Oceania,New Zealand,Fruits,High,2014-09-08
24,Europe,Moldova,Personal Care,Low,2016-05-07
25,Europe,France,Cosmetics,High,2017-05-22
26,Australia and Oceania,Kiribati,Fruits,Medium,2014-10-13
27,Sub-Saharan Africa,Mali,Fruits,Low,2010-05-07
28,Europe,Norway,Beverages,Constant,2014-07-18
29,Sub-Saharan Africa,The Gambia,Household,Low,2012-05-26
30,Europe,Switzerland,Cosmetics,Medium,2012-09-17
31,Sub-Saharan Africa,South Sudan,Personal Care,Constant,2013-12-29
32,Australia and Oceania,Australia,Office Supplies,Constant,2015-10-27
33,Asia,Myanmar,Household,High,2015-01-16
34,Sub-Saharan Africa,Djibouti,Snacks,Medium,2017-02-25
35,Middle East and North Africa,Syria,Fruits,Low,2011-11-22
36,Sub-Saharan Africa,The Gambia,Meat,Medium,2017-01-14
37,Central America and the Caribbean,Costa Rica,Personal Care,Low,2017-05-08
38,Asia,Brunei,Office Supplies,Low,2012-04-01
39,Europe,Bulgaria,Office Supplies,Medium,2012-02-16
40,Sub-Saharan Africa,Niger,Personal Care,High,2017-03-11
41,Middle East and North Africa,Azerbaijan,Cosmetics,Medium,2010-02-06
42,Sub-Saharan Africa,The Gambia,Cereal,High,2012-06-07

## Dates

Consider dataframe **`df2`**.
Change the Order Date column to a pandas datetime, with the format: year-month-day

(Keep the dataframe name **`df2`**)

* remember to add code that would allow for incorrect dates to be displayed as "NaT"

In [ ]:
# Enter code here
df2['Order Date'] = pd.to_datetime(df2['Order Date'], format="%Y-%m-%d", errors='coerce')
df2.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Monaco,Baby Food,H,2012-05-29,1373243.88,825738.04
1,Australia and Oceania,Samoa,Cosmetics,H,2013-07-20,2542187.82,1678540.98
2,Europe,Spain,Household,L,2012-10-21,2267963.02,747939.49
3,Middle East and North Africa,Lebanon,Clothes,L,NaT,282562.56,579000.96
4,Middle East and North Africa,Iran,Cosmetics,H,NaT,1708748.37,1128242.43

Remove all the rows in **`df2`** that contain NaT values in your "Order Date" column.

(Keep the dataframe name **df2**)

* NB: since you removed some rows, remember to reset your index!

In [ ]:
# Enter code here
df2 = df2[df2['Order Date'].notnull()].reset_index(drop=True)
df2.head()

,Region,Country,Item Type,Order Priority,Order Date,Total Cost,Total Profit
0,Europe,Monaco,Baby Food,H,2012-05-29,1373243.88,825738.04
1,Australia and Oceania,Samoa,Cosmetics,H,2013-07-20,2542187.82,1678540.98
2,Europe,Spain,Household,L,2012-10-21,2267963.02,747939.49
3,Sub-Saharan Africa,Zambia,Snacks,L,2011-01-04,398042.40,225246.90
4,Sub-Saharan Africa,Kenya,Vegetables,L,2012-03-18,587135.01,407630.41

## Dataframe --> CSV / Excel sheet

Write dataframe df1 to a csv named 'dataframe_1' and write it to the *pandas_df_prac* folder in your Drive

In [ ]:
# Enter code here

Write dataframe df2 to an excel sheet named 'dataframe_2' and write it to the *pandas_df_prac* folder in your Drive

In [ ]:
# Enter code here

## Additional exercises (if time allows)

Have a look at dataframe df3

In [ ]:
# Enter code here

Using Pandas commands, sort the Dataframe according to the Total Profit (from large to small profit)

Name this dataframe **sorted_df3**

In [ ]:
# Enter code here

What if we are only interested in the total cost and profit of the item types that are listed in dataframe **df3**? I.e., we want to generate a table consisting of three columns: *Item Type*, *Total Cost*, *Total Profit*

The *Item Type* column should list the each distinct item type once, and the *Total Cost* and *Total Profit* columns should give a summation of the costs associated with the given item types.

In [ ]:
# Enter code here